### ISSUE TITLE
Describe build requirements

### ISSUE THREAD

**Issue by kelnos** [esp-rs/esp32-wifi#3]
Hi, I know this project is very early-days, but I was hoping to help work on it, but it's really hard to get building.  First I tried rust 1.48.0, but changes to the unstable bits of the `alloc` and `core` crates failed the build.  For some reason (in hindsight, doesn't makes sense now) I thought using 1.49.0 would work better, but there's an LLVM issue with that which prevents it from working properly.  So I just tried rust 1.47.0 (and esp-idf 4.2; I re-ran the bindings generation and fixed up differences), but I'm still having one last issue:

```
error[E0277]: the trait bound `esp32::TIMG0: esp32_hal::timer::TimerGroup` is not satisfied
  --> examples/test.rs:35:23
   |
35 | static TIMER_HANDLER: TimerInterruptHandler<Timer<esp32::TIMG0, esp32_hal::timer::TimerLact>> =
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `esp32_hal::timer::TimerGroup` is not implemented for `esp32::TIMG0`
   | 
  ::: /home/brian/src/esp32-rust/esp32-hal/src/timer/mod.rs:40:24
   |
40 | pub struct Timer<TIMG: TimerGroup, INST: TimerInst> {
   |                        ---------- required by this bound in `esp32_hal::timer::Timer`
```

I've tried rolling the `esp32-hal` crate back to mid September of last year, but still hitting this issue. If I go any earlier, I run back into problems with the unstable `alloc` stuff.

Essentially I'm just trying to figure out what versions of rust and esp32-hal I should be using to be able to successfully compile this.  From there I'm happy to work on upgrading to esp-idf 4.2 and getting things like wifi scan results to work, and then eventually see about getting things to work with the latest rust and esp32-hal version.

Thanks for getting started on this project!  I'm really excited to be able to build wifi-enabled stuff using rust on esp32!

**Comment by kelnos** [comment]
I got a _little_ farther.  Built rust-xtensa 1.4.8 (required changes to esp32-hal and linked-list-allocator), went back down to esp-idf 4.1. However, I get linker errors:

```
error: linking with `xtensa-esp32-elf-gcc` failed: exit code: 1
  |
  = note: "xtensa-esp32-elf-gcc" "-Wl,--eh-frame-hdr" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/sysroot/lib/rustlib/xtensa-esp32-none-elf/lib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.0.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.1.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.10.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.11.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.12.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.13.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.14.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.15.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.2.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.3.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.4.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.5.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.6.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.7.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.8.rcgu.o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.test.6dczt6t7-cgu.9.rcgu.o" "-o" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/examples/test-c2cb04d2730b1113.1jmtncyjko2yp879.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/release/deps" "-L" "esp32-wifi-lib/esp32" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/build/esp32-2fc915ef9307eefd/out" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/build/xtensa-lx6-b93b259c554012b0/out" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/build/xtensa-lx6-rt-f10c1d895c5b65ca/out" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/build/esp32-hal-57bda688a762b309/out" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/build/esp32-4c3f59452846fad7/out" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/build/xtensa-lx-dbd1d147d496789b/out" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/build/xtensa-lx-rt-8d2c0d2e22c8142b/out" "-L" "/home/brian/src/esp32-rust/esp32-wifi/target/sysroot/lib/rustlib/xtensa-esp32-none-elf/lib" "-Wl,-Bstatic" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libesp32_wifi-582e6188a9680314.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx6-a45499bda6fc207f.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libnum_traits-0306da0d376a088c.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libesp32_hal-130b84a96c635364.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/liblinked_list_allocator-79cb3f0189202877.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libr0-8db2b85dc466427c.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libesp32-f104618f94fb90bb.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx-00a122684a21ba9a.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libspin-b4f7109626220cb1.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libmutex_trait-d07629f0ee42933e.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libvcell-690becd44a513da9.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libbare_metal-15bbd197bf778bcf.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libembedded_hal-bcbd4be8cd0afd15.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libvoid-2fd8f5edc5937610.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libnb-cb74e2d53a3ee34f.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libnb-f6a0df1f5554fdfc.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libcstr_core-967ccc98a3f25e8a.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libmemchr-3d6705afbd0a7c1e.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libcty-50df52090ffb0c44.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/sysroot/lib/rustlib/xtensa-esp32-none-elf/lib/liballoc-ebf240151b62794d.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/sysroot/lib/rustlib/xtensa-esp32-none-elf/lib/librustc_std_workspace_core-0d9d745aefbc7075.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/sysroot/lib/rustlib/xtensa-esp32-none-elf/lib/libcore-a624f92401a19e7d.rlib" "/home/brian/src/esp32-rust/esp32-wifi/target/sysroot/lib/rustlib/xtensa-esp32-none-elf/lib/libcompiler_builtins-d3d627904065a8e7.rlib" "-Wl,-Bdynamic" "-lnet80211" "-lpp" "-lrtc" "-lcore" "-lphy" "-lcoexist" "-nostartfiles" "-Wl,-Tlink.x"
  = note: /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_KernelExceptionVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.KernelExceptionVector.text+0x9): dangerous relocation: call0: call target out of range: __naked_kernel_exception
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_UserExceptionVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.UserExceptionVector.text+0x9): dangerous relocation: call0: call target out of range: __naked_user_exception
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_DoubleExceptionVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.DoubleExceptionVector.text+0x3): dangerous relocation: call0: call target out of range: __naked_double_exception
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_Level2InterruptVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.Level2InterruptVector.text+0x3): dangerous relocation: call0: call target out of range: __naked_level_2_interrupt
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_Level3InterruptVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.Level3InterruptVector.text+0x3): dangerous relocation: call0: call target out of range: __naked_level_3_interrupt
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_Level4InterruptVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.Level4InterruptVector.text+0x3): dangerous relocation: call0: call target out of range: __naked_level_4_interrupt
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_Level5InterruptVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.Level5InterruptVector.text+0x3): dangerous relocation: call0: call target out of range: __naked_level_5_interrupt
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_Level6InterruptVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.DebugExceptionVector.text+0x3): dangerous relocation: call0: call target out of range: __naked_level_6_interrupt
          /opt/xtensa/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/brian/src/esp32-rust/esp32-wifi/target/xtensa-esp32-none-elf/release/deps/libxtensa_lx_rt-939c76c4b2cfc29e.rlib(xtensa_lx_rt-939c76c4b2cfc29e.xtensa_lx_rt.cty8v98q-cgu.1.rcgu.o): in function `_Level7InterruptVector':
          xtensa_lx_rt.cty8v98q-cgu.1:(.NMIExceptionVector.text+0x3): dangerous relocation: call0: call target out of range: __naked_level_7_interrupt
          collect2: error: ld returned 1 exit status
```

Some googling suggests to add `-mlongcalls` (for gcc & esp-idf; looks like clang has `-mlong-calls`), but it doesn't seem like the llvm xtensa target supports it.

**Comment by kelnos** [comment]
After a bunch of trial and error I managed to get things building and running.  I think it'd be worthwhile to document things somewhere, but for now I have a gist with the steps that sorta generally work to get this running: https://gist.github.com/kelnos/e1db69cfda9e1a60feb46488e02a70a3
